# Generated by Django 3.2.2 on 2021-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_auto_20210802_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
